import { Metadata } from "next";
import { ReactNode } from "react";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type PropsType = {
  children: ReactNode;
};

export default function RootLayout({ children }: PropsType) {
  return children;
}
